### ISSUE TITLE
Update helm chart to support setting local data center value

### ISSUE THREAD

**Issue by wgalanciak** [CodeTogether-Inc/CodeTogether-Deployment#15]
It should be possible to set an optional localdatacenter value to allow users to customize data center in Cassandra setup.

**Comment by wgalanciak** [comment]
Work not started in sprint 2, moving to sprint 3.

**Comment by nmorenor** [comment]
pull request 
https://github.com/CodeTogether-Inc/CodeTogether-Deployment/pull/16
